import { Command } from 'commander';
import fs from 'fs';
import path from 'path';

import { runtimePathById } from '../runtime/index.mjs';
import {
  consoleColorize,
  initProcessCatchErrorLogger,
} from '../utils/index.mjs';

const ALL_PURGE_TARGETS = ['node_modules', 'dist'] as const;

type PurgeTarget = (typeof ALL_PURGE_TARGETS)[number];

/**
 * Walks the workspace tree collecting folders matching the requested targets.
 * Never descends into {node_modules}, so a {dist} folder generated by a
 * dependency is never matched — only folders generated by this workspace.
 */
function findFoldersToPurge(rootDir: string, targets: PurgeTarget[]) {
  const matchedPaths: string[] = [];

  function walk(currentDir: string) {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(currentDir, { withFileTypes: true });
    } catch {
      return;
    }

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      // NOTE: skip {.git} to avoid needlessly walking the whole object store
      if (entry.name === '.git') continue;

      const entryPath = path.join(currentDir, entry.name);

      if (entry.name === 'node_modules') {
        if (targets.includes('node_modules')) {
          matchedPaths.push(entryPath);
        }

        continue;
      }

      if (entry.name === 'dist') {
        if (targets.includes('dist')) {
          matchedPaths.push(entryPath);
        }

        continue;
      }

      walk(entryPath);
    }
  }

  walk(rootDir);

  return matchedPaths;
}

function registerPurgeCommand(program: Command) {
  program
    .command('purge')
    .description(
      'Purge workspace folders generated by this monorepo: node_modules and/or dist (a dist nested inside node_modules is never touched)',
    )
    .option(
      '-t, --target <types>',
      `Comma-separated targets to purge: ${ALL_PURGE_TARGETS.join(', ')} (default: all)`,
    )
    .action((options) => {
      console.log('\n🏗️  [mainset cli] purge');

      try {
        const targets = (
          options.target
            ? options.target
                .split(',')
                .map((target: string) => target.trim())
                .filter(Boolean)
            : ALL_PURGE_TARGETS
        ) as PurgeTarget[];

        const invalidTargets = targets.filter(
          (target) => !ALL_PURGE_TARGETS.includes(target),
        );

        if (invalidTargets.length > 0) {
          console.error(
            consoleColorize(
              'BRIGHT_YELLOW',
              `[mainset cli][purge] Unknown target(s): "${invalidTargets.join(', ')}". Valid targets: ${ALL_PURGE_TARGETS.join(', ')}`,
            ),
          );
          process.exit(1);
        }

        console.log(
          `🧹 Purging ${targets.join(' and ')} folders in "${runtimePathById.root}" ...\n`,
        );

        const foldersToPurge = findFoldersToPurge(
          runtimePathById.root,
          targets,
        );

        if (foldersToPurge.length === 0) {
          console.log('Nothing to purge.\n');
          return;
        }

        for (const folderPath of foldersToPurge) {
          console.log(`  - ${path.relative(runtimePathById.root, folderPath)}`);
          fs.rmSync(folderPath, { recursive: true, force: true });
        }

        console.log(
          `\n✅ Purge completed successfully. Removed ${foldersToPurge.length} folder(s).\n`,
        );
      } catch (error) {
        initProcessCatchErrorLogger('purge', error);
      }
    });
}

export { registerPurgeCommand };
